"""Tests for the blog post repository.

Each post under ``posts/<name>/`` is fully self-contained (its own
``environment.yml``, ``notebook.ipynb``, ``main.md``, ``scripts/``, ``data/``);
posts never depend on one another. CI therefore builds one isolated conda env
per post and runs the tests below scoped to a single post at a time (see
``.github/workflows/Notebooks.yml``). Set ``BLOG_TEST_POST=<name>`` to restrict
discovery to one post locally too; unset, all posts are collected.

Three checks run per post (the third only when the notebook regenerates figures):

1. ``test_notebook_runs`` – executes ``notebook.ipynb`` top-to-bottom **in the
   post's own directory**, which regenerates ``figures/*.png`` as a side effect
   (every notebook calls ``os.makedirs(FIG, exist_ok=True)`` before ``savefig``).
   It runs in *strict* mode first (``nbval --nbval``: stored outputs must
   reproduce exactly). Only if strict fails does it fall back to *lax* mode
   (``nbval --nbval-lax``: must merely execute) to classify the failure:
     - lax also fails  -> the notebook does not execute (a real break);
     - lax passes      -> it executes but stored outputs are stale or
                          nondeterministic (re-run and commit, or mark the cell
                          ``# NBVAL_IGNORE_OUTPUT``).
   In the common case (strict passes) the notebook executes exactly **once** per
   CI run. Opt out of strict via ``POSTS_TO_EXCLUDE_NOTEBOOK_STRICT`` (falls back
   to lax as the primary check) and out of lax via
   ``POSTS_TO_EXCLUDE_NOTEBOOK_LAX``.
2. ``test_post_pdf_builds`` – ``main.md`` renders to a PDF with ``pandoc`` using
   the bundled Eisvogel template (``templates/eisvogel.latex``). ``figures/`` is
   git-ignored (the repo tracks code + prose, not artifacts), so the figures are
   obtained, in order of preference, from: the notebook run earlier in the same
   leg (which regenerates them in place); the committed web copies under
   ``site/images/posts/<slug>/`` copied in by ``_ensure_figures`` (a prose-only
   leg that skips the notebook); or, as a last resort, a one-off notebook
   execution. Exclude via ``POSTS_TO_EXCLUDE_MARKDOWN``.
3. ``test_committed_figures_current`` – compares the committed web figures under
   ``site/images/posts/<slug>/`` against the figures just regenerated by check 1,
   failing if they've drifted (an analysis change never re-synced to the site).
   RMS pixel diff with tolerance ``FIGURE_DRIFT_TOL``. Only meaningful on notebook
   legs (needs freshly generated figures). Exclude via
   ``POSTS_TO_EXCLUDE_FIGURE_DRIFT``.

nbval never writes back to the ``.ipynb``, so running it on the committed
notebook compares live outputs against the committed outputs (not against
themselves) and leaves the file untouched.

Posts are discovered automatically, so adding a new ``posts/<name>/`` directory
needs no changes here.

Notes for authoring notebooks (these affect the strict check):
  - Add ``# NBVAL_IGNORE_OUTPUT`` at the top of a cell whose output is not
    expected to be reproducible (timestamps, random values, plots, ...).
  - Add ``# NBVAL_CHECK_OUTPUT`` at the top of a cell whose output *should* be
    compared even when running in lax mode.
"""

import importlib.util
import os
import shutil
import subprocess
import sys

import pytest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
POSTS_DIR = os.path.join(REPO_ROOT, "posts")

# Per-check opt-out lists. Add a post's directory name (e.g. "post1") to skip it
# for that one check only; the other checks still run for that post.
POSTS_TO_EXCLUDE_MARKDOWN = set()          #* posts to skip in test_post_pdf_builds
POSTS_TO_EXCLUDE_NOTEBOOK_LAX = set()      #* posts to skip in the lax fallback
POSTS_TO_EXCLUDE_NOTEBOOK_STRICT = set()   #* posts to skip in the strict check
POSTS_TO_EXCLUDE_FIGURE_DRIFT = set()      #* posts to skip in the figure-drift check

NBVAL_AVAILABLE = importlib.util.find_spec("nbval") is not None
MPL_AVAILABLE = importlib.util.find_spec("matplotlib") is not None
PANDOC_BIN = shutil.which("pandoc")
LATEX_BIN = shutil.which("xelatex") or shutil.which("lualatex") or shutil.which("pdflatex")
EISVOGEL_TEMPLATE = os.path.join(REPO_ROOT, "templates", "eisvogel.latex")
SITE_IMAGES_DIR = os.path.join(REPO_ROOT, "site", "images", "posts")

# RMS pixel tolerance for the figure-drift check (0-255 scale). Lenient enough
# to tolerate minor cross-machine font/antialiasing differences, tight enough to
# flag a materially changed figure. Override with the FIGURE_DRIFT_TOL env var
# (e.g. raise it if CI's freetype/matplotlib differs from the machine that
# generated the committed PNGs and the check is too twitchy).
FIGURE_DRIFT_TOL = float(os.environ.get("FIGURE_DRIFT_TOL", "10"))

# When set, restrict discovery to a single post. CI sets this per matrix leg so
# each isolated env only runs its own post's tests.
ONLY_POST = os.environ.get("BLOG_TEST_POST") or None


def discover(filename):
    """Return (post_name, path) for every ``posts/<name>/<filename>`` file.

    Honors ``BLOG_TEST_POST`` to scope collection to a single post.
    """
    if not os.path.isdir(POSTS_DIR):
        return []
    found = []
    for name in sorted(os.listdir(POSTS_DIR)):
        if ONLY_POST and name != ONLY_POST:
            continue
        path = os.path.join(POSTS_DIR, name, filename)
        if os.path.isfile(path):
            found.append((name, path))
    return found


NOTEBOOKS = discover("notebook.ipynb")
MD_FILES = discover("main.md")


def run_nbval(notebook_path, strict):
    """Execute ``notebook_path`` with nbval in a fresh subprocess.

    Runs in the notebook's own directory so relative ``savefig`` calls populate
    ``posts/<name>/figures/``. Running pytest as a subprocess (rather than a
    nested ``pytest.main`` call) keeps the inner nbval session isolated from the
    outer one, which is what made an earlier version of these tests unreliable.
    nbval does not modify the notebook file, so the committed outputs stay the
    comparison baseline.
    """
    mode = "--nbval" if strict else "--nbval-lax"
    cmd = [
        sys.executable,
        "-m",
        "pytest",
        mode,
        "--nbval-current-env",  # use the env pytest runs in, ignore kernelspec
        "--tb=short",
        "-p",
        "no:cacheprovider",
        notebook_path,
    ]
    result = subprocess.run(cmd, cwd=os.path.dirname(notebook_path))
    return result.returncode


@pytest.mark.skipif(not NBVAL_AVAILABLE, reason="nbval plugin not installed")
@pytest.mark.parametrize(
    "post_name,notebook_path",
    NOTEBOOKS,
    ids=[name for name, _ in NOTEBOOKS],
)
def test_notebook_runs(post_name, notebook_path):
    """Execute the post notebook (regenerating figures); strict, then lax.

    Strict runs first and, on success, is the only execution. Lax runs only to
    diagnose a strict failure. Defined before ``test_post_pdf_builds`` so the
    figures it produces exist by the time the PDF build needs them.
    """
    do_strict = post_name not in POSTS_TO_EXCLUDE_NOTEBOOK_STRICT
    do_lax = post_name not in POSTS_TO_EXCLUDE_NOTEBOOK_LAX

    if not do_strict and not do_lax:
        pytest.skip(f"{post_name} excluded from both notebook checks")

    # Strict excluded -> lax is the primary (and only) check.
    if not do_strict:
        rc = run_nbval(notebook_path, strict=False)
        assert rc == 0, f"Notebook for {post_name} failed to execute (lax)"
        return

    rc_strict = run_nbval(notebook_path, strict=True)
    if rc_strict == 0:
        return  # reproduced stored outputs exactly; single execution, done.

    if not do_lax:
        pytest.fail(
            f"Notebook for {post_name} did not reproduce its stored outputs "
            f"(strict), and lax is disabled for this post."
        )

    # Strict failed and lax is enabled: classify the failure with one lax run.
    rc_lax = run_nbval(notebook_path, strict=False)
    if rc_lax == 0:
        pytest.fail(
            f"Notebook for {post_name} executes cleanly but its stored outputs "
            f"are stale or nondeterministic (strict mismatch). Re-run the "
            f"notebook and commit the outputs, or mark nondeterministic cells "
            f"with '# NBVAL_IGNORE_OUTPUT'."
        )
    pytest.fail(f"Notebook for {post_name} failed to execute (strict and lax).")


@pytest.mark.skipif(not MPL_AVAILABLE, reason="matplotlib not installed")
@pytest.mark.parametrize(
    "post_name,notebook_path",
    NOTEBOOKS,
    ids=[name for name, _ in NOTEBOOKS],
)
def test_committed_figures_current(tmp_path, post_name, notebook_path):
    """Committed site figures still match freshly generated ones (notebook legs).

    ``test_notebook_runs`` executes the notebook earlier in this leg and leaves
    fresh PNGs in ``posts/<slug>/figures/``. This compares each *committed*
    figure under ``site/images/posts/<slug>/`` — what the deployed site serves
    and the PDF embeds — against its freshly generated counterpart, so an
    analysis change that was never re-synced to the site (via
    ``scripts/sync_posts.py``) is caught. Comparison is an RMS pixel diff with a
    tolerance (``FIGURE_DRIFT_TOL``) so minor cross-machine rendering differences
    don't false-positive.

    Only meaningful on notebook legs; in CI the prose-only leg runs just the PDF
    build, so this is not collected there. Extra generated figures with no
    committed copy (an unreferenced plot) are ignored — we only guard published
    figures. Skip a post via ``POSTS_TO_EXCLUDE_FIGURE_DRIFT``.
    """
    if post_name in POSTS_TO_EXCLUDE_FIGURE_DRIFT:
        pytest.skip(f"{post_name} is in POSTS_TO_EXCLUDE_FIGURE_DRIFT")

    from matplotlib.testing.compare import compare_images

    site_dir = os.path.join(SITE_IMAGES_DIR, post_name)
    committed = (
        sorted(f for f in os.listdir(site_dir) if f.endswith(".png"))
        if os.path.isdir(site_dir)
        else []
    )
    if not committed:
        pytest.skip(f"no committed site figures for {post_name}")

    fig_dir = os.path.join(os.path.dirname(notebook_path), "figures")
    generated = set(os.listdir(fig_dir)) if os.path.isdir(fig_dir) else set()
    if not generated:
        pytest.skip(
            f"figures/ empty for {post_name} — test_notebook_runs did not "
            f"regenerate figures in this run, so there is nothing to compare"
        )

    missing, drifted = [], []
    for name in committed:
        if name not in generated:
            missing.append(name)
            continue
        # Copy both into tmp so compare_images' diff artifacts don't touch the repo.
        expected = os.path.join(tmp_path, f"committed_{name}")
        actual = os.path.join(tmp_path, f"generated_{name}")
        shutil.copy2(os.path.join(site_dir, name), expected)
        shutil.copy2(os.path.join(fig_dir, name), actual)
        try:
            result = compare_images(
                expected, actual, tol=FIGURE_DRIFT_TOL, in_decorator=True
            )
        except Exception as exc:  # e.g. differing image sizes -> definitely drift
            drifted.append(f"{name} ({exc})")
            continue
        if result is not None:  # dict with 'rms' when it exceeds tolerance
            drifted.append(f"{name} (RMS {result['rms']:.1f} > tol {FIGURE_DRIFT_TOL})")

    problems = []
    if missing:
        problems.append(
            "committed figures no longer produced by the notebook: "
            + ", ".join(missing)
        )
    if drifted:
        problems.append(
            "figures differ from committed site copies: " + "; ".join(drifted)
        )
    assert not problems, (
        f"{post_name}: the committed site/images/posts/{post_name}/ figures are "
        f"stale relative to the current notebook. Re-run scripts/sync_posts.py "
        f"and commit the updated images (or, for expected rendering-only "
        f"differences, raise FIGURE_DRIFT_TOL or add the post to "
        f"POSTS_TO_EXCLUDE_FIGURE_DRIFT).\n  " + "\n  ".join(problems)
    )


def _ensure_figures(post_dir):
    """Make sure ``posts/<slug>/figures/`` holds the figures ``main.md`` embeds.

    ``figures/`` is git-ignored, so it may be empty on a fresh checkout. Fill it
    without re-running the notebook when we can:

    1. If ``test_notebook_runs`` already executed in this leg, the figures are
       there — nothing to do.
    2. Otherwise (a prose-only leg) copy the committed web copies from
       ``site/images/posts/<slug>/``. ``sync_posts.py`` populates that directory
       with exactly the figures the article references, which is the set
       ``main.md`` embeds — so this is sufficient for the PDF build and needs no
       post dependencies.
    3. As a last resort (no committed copy anywhere) execute the notebook once
       via nbconvert to ``--stdout`` (discarded, so the committed ``.ipynb`` is
       never modified) purely for the ``savefig`` side effect.
    """
    figdir = os.path.join(post_dir, "figures")
    if os.path.isdir(figdir) and any(f.endswith(".png") for f in os.listdir(figdir)):
        return  # already produced by test_notebook_runs

    slug = os.path.basename(os.path.normpath(post_dir))
    site_figs = os.path.join(REPO_ROOT, "site", "images", "posts", slug)
    if os.path.isdir(site_figs):
        pngs = [f for f in os.listdir(site_figs) if f.endswith(".png")]
        if pngs:
            os.makedirs(figdir, exist_ok=True)
            for f in pngs:
                shutil.copy2(os.path.join(site_figs, f), os.path.join(figdir, f))
            return

    notebook = os.path.join(post_dir, "notebook.ipynb")
    if not os.path.isfile(notebook):
        return
    subprocess.run(
        [
            sys.executable,
            "-m",
            "nbconvert",
            "--to",
            "notebook",
            "--execute",
            "--stdout",
            "notebook.ipynb",
        ],
        cwd=post_dir,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


@pytest.mark.skipif(not PANDOC_BIN, reason="pandoc not installed")
@pytest.mark.skipif(not LATEX_BIN, reason="no LaTeX engine on PATH")
@pytest.mark.skipif(
    not os.path.isfile(EISVOGEL_TEMPLATE),
    reason="templates/eisvogel.latex missing (run scripts/download_eisvogel.sh)",
)
@pytest.mark.parametrize(
    "post_name,md_path",
    MD_FILES,
    ids=[name for name, _ in MD_FILES],
)
def test_post_pdf_builds(tmp_path, post_name, md_path):
    """Each post's main.md renders to a PDF via pandoc + the Eisvogel template."""
    if post_name in POSTS_TO_EXCLUDE_MARKDOWN:
        pytest.skip(f"{post_name} is in POSTS_TO_EXCLUDE_MARKDOWN")

    post_dir = os.path.dirname(md_path)
    _ensure_figures(post_dir)

    output_pdf = os.path.join(tmp_path, f"{post_name}.pdf")
    cmd = [
        PANDOC_BIN,
        "main.md",
        "--from",
        "markdown",
        "--template",
        EISVOGEL_TEMPLATE,
        "--listings",
        # Resolve [@key] citations and render the reference list from the post's
        # references.bib. The bibliography/csl paths come from the main.md front
        # matter, so a post with no citations simply produces no bibliography.
        "--citeproc",
        "-o",
        output_pdf,
    ]
    # Run in the post directory so relative images/links resolve.
    result = subprocess.run(cmd, cwd=post_dir, capture_output=True, text=True)
    assert result.returncode == 0, (
        f"pandoc build failed for {post_name}:\n{result.stderr[-3000:]}"
    )
    assert os.path.isfile(output_pdf), f"No PDF produced for {post_name}"
